// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _26Changingthemodeladdsubsribedtocustomer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_26Changingthemodeladdsubsribedtocustomer));
        
        string IMigrationMetadata.Id
        {
            get { return "201707220724591_26.Changing the model (add subsribed to customer)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
